# Generated by Django 4.0.5 on 2022-06-13 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_remove_indexpage_welcom_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='board_desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='board',
            old_name='board_name',
            new_name='name',
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.board')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('date_posted', models.DateTimeField()),
                ('url', models.URLField()),
                ('url_title', models.TextField()),
                ('post_text', models.TextField()),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.board')),
                ('tags', models.ManyToManyField(to='board.tag')),
            ],
        ),
    ]
