# Generated by Django 4.0.4 on 2022-06-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_rename_board_desc_board_desc_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='board',
            name='rules',
            field=models.TextField(default='rules'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='board',
            constraint=models.UniqueConstraint(fields=('name',), name='unique board'),
        ),
    ]
