# Generated by Django 4.0.4 on 2022-06-25 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_alter_post_post_text_alter_post_url_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(limit_choices_to={'board': models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.board')}, to='board.tag'),
        ),
    ]
