# Generated by Django 4.0.4 on 2022-06-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_alter_post_options_alter_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='show_in_header',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
