# Generated by Django 4.0.5 on 2022-06-26 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_tag_show_in_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='show_in_header',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField()),
                ('post_text', models.TextField(max_length=600)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.post')),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
    ]
