# Generated by Django 3.2.13 on 2022-06-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_auto_20220628_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexpage',
            name='default_index',
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='is_default',
            field=models.BooleanField(),
        ),
    ]
